### ISSUE TITLE
Support Older Types

### ISSUE THREAD

**Issue by wlan0** [koki/short#10]
Support older types.

For eg. 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hostexec
  labels:
    app: hostexec
spec:
  containers:
  - name: hostexec
    image: gcr.io/kubernetes-e2e-test-images/hostexec-amd64:1.0
  securityContext:
    hostNetwork: true
```
hostNetwork is lost because it has moved to PodSpec now, and is not a part of securityContext anymore
