### ISSUE TITLE
Service healthcheck nodeport

### ISSUE THREAD

**Issue by wlan0** [koki/short#101]
```
wlan0@wlan0:~/code/go/src/github.com/koki/short/testdata/services$ ../../bin/short -f service_spec_with_health_check_port.yaml 
service:
  annotations:
    meta: _test
  cluster: test_cluster
  labels:
    app: meta_test
  name: meta_test
  namespace: test
  version: v1

wlan0@wlan0:~/code/go/src/github.com/koki/short/testdata/services$ cat service_spec_with_health_check_port.yaml 
apiVersion: v1
kind: Service
metadata:
  name: meta_test
  labels:
    app: meta_test
  annotations:
    meta: _test 
  namespace: test
  clusterName: test_cluster
spec:
  healthCheckNodePort: 32
```
