### ISSUE TITLE
Git Repo Volume Source short

### ISSUE THREAD

**Issue by wlan0** [koki/short#141]
Currently, the short format looks like this 

```yaml
pod:
  annotations:
    meta: _test
  cluster: test_cluster
  labels:
    app: meta_test
  name: meta_test
  namespace: test
  version: v1
  volumes:
    test_volume:
      directory: testdata
      revision: master
      vol_id: github.com/koki
      vol_type: git
```

It would be ideal to call

`directory` as `dir` 
and
`revision` as `rev`

Please change it
