### ISSUE TITLE
Gluster FS Volume Source short

### ISSUE THREAD

**Issue by wlan0** [koki/short#142]
The glusterfs volume source short hand equivalent looks like 

```yaml
pod:
  annotations:
    meta: _test
  cluster: test_cluster
  labels:
    app: meta_test
  name: meta_test
  namespace: test
  version: v1
  volumes:
    test_volume:
      endpoints: endpointsName
      ro: true
      vol_id: /path/to/gluster/vol
      vol_type: glusterfs
```

It is un-intuitive to set the Path field using the key `vol_id`. This key should be called `path` 

Also, I'm not sure if `endpoints` can be renamed to `endpoint`. Since it seems to me like its just one string (which is it's kubernetes type), and using the plural form is confusing, and makes it seem like a list. I don't know why they designed it this way. 

Can you look into why `endpoints` is plural and comment here.
