### ISSUE TITLE
Zero value fields should not be printed 

### ISSUE THREAD

**Issue by wlan0** [koki/short#38]
On conversion and reversion, the Zero value fields with values like "null" or replicas: 0 should not be printed. 

This was from my conversion from kube to koki first and then back.

```yaml
- apiVersion: extensions/v1beta1
  kind: ReplicaSet
  metadata:
    creationTimestamp: null
    name: frontend
  spec:
    replicas: 3
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: guestbook
          tier: frontend
      spec:
        containers:
        - env:
          - name: GET_HOSTS_FROM
            value: dns
          image: gcr.io/google_samples/gb-frontend:v3
          name: php-redis
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
  status:
    replicas: 0
```

status should'nt have shown
similarly, creationTimeStamp key should'nt have shown in the output
