### ISSUE TITLE
env var syntax

### ISSUE THREAD

**Issue by wlan0** [koki/short#48]
environment variables should be of type 
```
[]MapOrString
```

if the env var is a key value pair
then the representation will just be

```
env:
   - KEY=VALUE
```
if there is a from syntax, then the env var will look like

```
env:
  - from: secret:secret_name
    key: KEY
  - KEY=VALUE
```
