### ISSUE TITLE
Service port when only set in the ports field doesn't work

### ISSUE THREAD

**Issue by wlan0** [koki/short#54]
```yaml
 service:
   version: v1
   name: docs
   #port: 80:3000
   selector:
      app: docs.koki.io
   type: LoadBalancer
   ports:
   - 80:3000 
```

The above yaml doesn't parse into a kubernetes type, but this does 

```yaml
service:
  version: v1
  name: docs
  port: 80:3000
  selector:
    app: docs.koki.io
  type: LoadBalancer
  #ports:
  # - 80:3000
```

Both should work
