### ISSUE TITLE
Output on invalid input

### ISSUE THREAD

**Issue by wlan0** [koki/short#55]
The output when I get, when I provide this yaml

```yaml
service:
  version: v1
  name: docs
  #port: 80:3000
  selector:
    app: docs.koki.io
  type: LoadBalancer
  ports:
   - 80:3000
```
is

```
null

```

The output should be more informative.
