### ISSUE TITLE
Deployment creation labels

### ISSUE THREAD

**Issue by wlan0** [koki/short#56]
If the user provides no labels for a deployment like so:

```yaml
deployment:
 name: doctor
 version: extensions/v1beta1
 replicas: 1
```

Then the resulting kube deployment should have the selector, not the label (like the ouput I get today)
```yaml
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: doctor
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          koki.io/selector.name: doctor
      spec:
        containers: null
  status: {}
```

If a user provides a label, then the label, selector and the podTemplate label all should have the same value.

If the user provides a label and a selector, then the podTemplate should have the value in selector.
