### ISSUE TITLE
Env Var cannot have URLs

### ISSUE THREAD

**Issue by wlan0** [koki/short#57]
Our Env var format cannot take URLs as values.

If I provide this deployment yaml

```yaml
deployment:
 name: doctor
 version: extensions/v1beta1
 replicas: 1
 labels:
   app: docs.koki.io
 containers:
  - name: doctor
    env: 
     - IS_DOCKER=true
     - DATABASE_URL=postgresql://postgres:postgres@posgres/posgres?pool=5
     - RAILS_ENV=prod
```

then it returns the crappy error message
```
null

```

If I comment out this one env var, then it shows an output

```yaml
deployment:
 name: doctor
 version: extensions/v1beta1
 replicas: 1
 labels:
   app: docs.koki.io
 containers:
  - name: doctor
    env: 
     - IS_DOCKER=true
#     - DATABASE_URL=postgresql://postgres:postgres@posgres/posgres?pool=5
     - RAILS_ENV=prod
```

So, that URL cannot be parsed by our system. It gets confused by the ":". It should choose "="  mode or ":" mode based on which occurs first.
