### ISSUE TITLE
Container args int value

### ISSUE THREAD

**Issue by wlan0** [koki/short#58]
If I set int values into container args, it breaks

this example breaks currently

```yaml
deployment:
 name: doctor
 version: extensions/v1beta1
 replicas: 1
 labels:
   app: docs.koki.io
 containers:
  - name: doctor
    env: 
     - IS_DOCKER=true
#     - DATABASE_URL=postgresql://postgres:postgres@posgres/posgres?pool=5
     - RAILS_ENV=prod
    image: minio/doctor
    args: 
     - bundle
     - exec
     - rails
     - s
     - -p
     - 3000

```
