### ISSUE TITLE
Service Type LB bug

### ISSUE THREAD

**Issue by wlan0** [koki/short#60]
Service Type LB changes to Service Type ClusterIP

This input yaml

```yaml
service:
  version: v1
  name: docs
  port: 80:3000
  selector:
    app: docs.koki.io
  type: LoadBalancer
```

gets transformed to 

```yaml
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: docs
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: docs.koki.io
    type: ClusterIP
  status:
    loadBalancer: {}
```
