### ISSUE TITLE
hostname and subdomain

### ISSUE THREAD

**Issue by wlan0** [koki/short#96]
```
apiVersion: v1
kind: Pod
metadata:
  name: meta_test
  labels:
    app: meta_test
  annotations:
    meta: _test 
  namespace: test
  clusterName: test_cluster
spec:
  subdomain: docs
  hostname: koki.io
```

This should result in fqdn of `docs.koki.io`

The current result looks like

```yaml
pod:
  annotations:
    meta: _test
  cluster: test_cluster
  hostname: koki.io.docs
  labels:
    app: meta_test
  name: meta_test
  namespace: test
  version: v1
```
