### ISSUE TITLE
Tolerations

### ISSUE THREAD

**Issue by wlan0** [koki/short#97]
```
../../bin/short -f pod_spec_with_toleration.yaml 
pod:
  annotations:
    meta: _test
  cluster: test_cluster
  labels:
    app: meta_test
  name: meta_test
  namespace: test
  tolerations:
  - Selector: =value:NoSchedule
  - Selector: key:NoSchedule
  version: v1

wlan0@wlan0:~/code/go/src/github.com/koki/short/testdata/pods$ cat pod_spec_with_toleration.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: meta_test
  labels:
    app: meta_test
  annotations:
    meta: _test 
  namespace: test
  clusterName: test_cluster
spec:
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"
  - key: "key"
    operator: "Exists"
    effect: "NoSchedule"
```
