### ISSUE TITLE
Priority Class Name

### ISSUE THREAD

**Issue by wlan0** [koki/short#98]
```
wlan0@wlan0:~/code/go/src/github.com/koki/short/testdata/pods$ ../../bin/short -f pod_spec_with_priority_class_name.yaml 
pod:
  annotations:
    meta: _test
  cluster: test_cluster
  labels:
    app: meta_test
  name: meta_test
  namespace: test
  version: v1

wlan0@wlan0:~/code/go/src/github.com/koki/short/testdata/pods$ cat pod_spec_with_priority_class_name.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: meta_test
  labels:
    app: meta_test
  annotations:
    meta: _test 
  namespace: test
  clusterName: test_cluster
spec:
  priorityClassName: SYSTEM

```
