### ISSUE TITLE
Priority value

### ISSUE THREAD

**Issue by wlan0** [koki/short#99]
```
../../bin/short -f pod_spec_with_priority.yaml 
pod:
  annotations:
    meta: _test
  cluster: test_cluster
  labels:
    app: meta_test
  name: meta_test
  namespace: test
  version: v1

wlan0@wlan0:~/code/go/src/github.com/koki/short/testdata/pods$ cat pod_spec_with_priority.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: meta_test
  labels:
    app: meta_test
  annotations:
    meta: _test 
  namespace: test
  clusterName: test_cluster
spec:
  priority: 3
```
